CREATE DATABASE AnimalCare;
GO
USE AnimalCare;
GO
CREATE TABLE animals (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    nome NVARCHAR(255) NOT NULL,
    descricao TEXT NULL,
    data_nascimento DATE NULL,
    especie NVARCHAR(100) NOT NULL,
    habitat NVARCHAR(100) NULL,
    pais_origem NVARCHAR(100) NULL,
    created_at DATETIMEOFFSET NULL DEFAULT SYSDATETIMEOFFSET(),
    updated_at DATETIMEOFFSET NULL
);
GO
CREATE TABLE cuidados (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    nome NVARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    frequencia NVARCHAR(100) NOT NULL,
    created_at DATETIMEOFFSET NULL DEFAULT SYSDATETIMEOFFSET(),
    updated_at DATETIMEOFFSET NULL
);
GO